### PR TITLE
Removed rappdirs dependency

### PR DESCRIPTION
**Pull request by kpiyush04**
- [x] Removed rappdirs dependency
- [x] Added tools::R_user_dir() for storing R-related user-specific data, configuration and cache files.

issue: #3

### CODE REVIEW

**Comment by llrs** [comment]
Nice first PR! Precise and just a good commit. Is the resulting path the same or in a similar directory? I haven't installed R 4.1.0 and cannot test it yet.

**Comment by kpiyush04** [comment]
> Nice first PR! Precise and just a good commit. Is the resulting path the same or in a similar directory? I haven't installed R 4.1.0 and cannot test it yet.

The resulting path is the same.

**Comment by llrs** [comment]
Let's check. Does this return TRUE?

```r
tools::R_user_dir("bugRzilla") == rappdirs::user_cache_dir("bugRzilla")
```

**Comment by kpiyush04** [comment]
> Let's check. Does this return TRUE?
> 
> ```r
> tools::R_user_dir("bugRzilla") == rappdirs::user_cache_dir("bugRzilla")
> ```

It returns False.

image

**Comment by llrs** [comment]
So they are not the same path, and as we can see the path is not similar, one is to the cache folder and the other is to the data folder. Read the documentation to make the path point to the cache folder.

**Comment by llrs** [comment]
Great that fixed it.

**Pull request merged**
